In [ ]:
import torch.autograd

In [ ]:
import numpy as np

In [ ]:
# Variable: data, grad, grad_fn, requires_grad, is_leaf
# Tensor: Variable +dtype(float, cuda.float), shape, device

In [ ]:
flag = True

In [ ]:
if flag==True:
    device = 'cuda'
else:
    device = 'cpu'
print(device)

In [ ]:
# Create Tensor

In [ ]:
# 1.1.torch.tensor(array,)

In [48]:
arr = np.ones((3,3,4))
t = torch.tensor(arr, device=device)
print("t.data:{}\nt.grad:{}\nt.grad_fn:{}\nt.rquires_grad:{}\nt.is_leaf:{}\nt.dtype:{}\nt.shape:{}\nt.device:{}\n".format(
    t.data, t.grad, t.grad_fn, t.requires_grad, t.is_leaf, t.dtype, t.shape, t.device))

t.data:tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], device='cuda:0', dtype=torch.float64)
t.grad:None
t.grad_fn:None
t.rquires_grad:False
t.is_leaf:True
t.dtype:torch.float64
t.shape:torch.Size([3, 3, 4])
t.device:cuda:0



In [ ]:
# 1.2.torch.zeros(size, out),torch.ones(size, out)

In [ ]:
out_t = torch.tensor([1])

In [ ]:
t_0 = torch.zeros((3,3), out=out_t)

In [ ]:
t_1 = torch.ones((2,2))

In [ ]:
print("out_t:\n{}\nt_0:\n{}\nt1:\n{}\n".format(out_t
                                              , t_0, t_1))

In [ ]:
# 1.3. torch.from_numpy

In [ ]:
arr = np.array([[1,2,3],[4,5,6]], dtype=float)
t = torch.from_numpy(arr)
arr[0][0] = -1
print("arr:\n{}\nt:\n{}\n".format(arr, t))

In [ ]:
# 1.4. torch.full(size, data)

In [ ]:
t = torch.full((3,3), 5)
print("t:\n{}\n".format(t))

In [49]:
# 1.5. torch.arange([begin, end), delta)
# while(begin + delta < end):
#     begin += delta

In [54]:
t = torch.arange(2, 10, 2, device=device)
print(t)

tensor([2, 4, 6, 8], device='cuda:0')


In [55]:
# 1.6 torch.linspace([begin, end], step)
# d = (end - begin)/(step - 1)

In [57]:
t = torch.linspace(2, 10, 5, dtype=torch.float32)
print(t)

tensor([ 2.,  4.,  6.,  8., 10.])


In [58]:
# 1.7 torch.eye(n,m)
# matrix I = n * m

In [59]:
t = torch.eye(3,3)
print(t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [60]:
# 1.8 torch.normal(std, mean)

In [61]:
mean = torch.ones(5)
std = torch.ones(5)
t = torch.normal(mean, std)
print(t)

tensor([ 1.0263,  2.4674,  0.5253, -0.0941,  1.0976])
